version: '3'

services:

  ## MongoDB storage
  storage:
    build: 
      context: ./storage
      args:
        DB_USER: statusweb
        DB_PASS: E8Zrmqg59xTowNgVdZFVTj
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: eXAVMdGZododxj4wMr9w
      MONGO_INITDB_DATABASE: admin
    expose:
      - 27017
    volumes:
      - advanced-console_db:/data/db
      - advanced-console_configdb:/data/configdb

  ##  API back-end
  api:
    build: ./server
    environment:
      DB_HOST: storage
      DB_USER: statusweb
      DB_PASS: E8Zrmqg59xTowNgVdZFVTj
      JWT_SECRET: RBsjHDcRVdsbuEt7FYAKaNF52tCWKQ8NKYjiMa7gLF69Ab7cv5t6UnzYyLWRFMGL9
    expose:
      - 3030
    links:
      - storage

  ## Web front-end
  client:
    build: ./client
    environment:
      SERVER_HOST: localhost
      API_HOST: api
      API_PORT: 3030
    expose:
      - 80
      - 443
    ports:
      - 80:80
      - 443:443
    links:
      - api
    volumes:
      - ./privkey.pem:/etc/ssl/localhost/privkey.pem
      - ./fullchain.pem:/etc/ssl/localhost/fullchain.pem
volumes:  
  advanced-console_db:
  advanced-console_configdb: